import { HTTP_METHOD, Prisma } from '@prisma/client'

const base = '/api/v1/'
const service = base + 'service'
const booking = base + 'booking'
const numberRegex = '/\\d+'
const stringRegex = '/.+'
const templateAvailability = base + 'template-availability'
const scopePrefix = 'legalerConnect.'
const user = base + 'user'
const workspace = base + 'workspace'
const meeting = base + 'meeting'
const room = base + 'room'
const sharing = base + 'sharing'
export const actions: Prisma.actionCreateManyArgs['data'] = [
  // { path: base + 'server.location', method: HTTP_METHOD['GET'], name: '' },
  { action_id: 1, name: 'service', scope: scopePrefix + 'service.all' },
  {
    action_id: 2,
    path: service,
    method: HTTP_METHOD[HTTP_METHOD['POST']],
    name: 'create',
    scope: scopePrefix + 'service.write',
    parent_id: 1,
  },
  {
    action_id: 3,
    path: service + numberRegex,
    method: HTTP_METHOD['PATCH'],
    name: 'edit',
    scope: scopePrefix + 'service.write',
    parent_id: 1,
  },
  {
    action_id: 4,
    path: service + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'delete',
    scope: scopePrefix + 'service.write',
    parent_id: 1,
  },
  {
    action_id: 5,
    path: service + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get one',
    scope: scopePrefix + 'service.read',
    parent_id: 1,
  },
  {
    action_id: 6,
    path: service,
    method: HTTP_METHOD['GET'],
    name: 'get list',
    scope: scopePrefix + 'service.read',
    parent_id: 1,
  },
  {
    path: service + '/spread-time' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get available times for booking',
    scope: scopePrefix + 'service.read',
    parent_id: 1,
    action_id: 7,
  },
  { action_id: 8, name: 'booking', scope: scopePrefix + 'booking.all' },
  {
    action_id: 9,
    path: booking,
    method: HTTP_METHOD['POST'],
    name: 'create',
    scope: scopePrefix + 'booking.write',
    parent_id: 8,
  },
  {
    action_id: 10,
    path: booking + numberRegex,
    method: HTTP_METHOD['PATCH'],
    name: 'edit',
    scope: scopePrefix + 'booking.write',
    parent_id: 8,
  },
  {
    action_id: 11,
    path: booking + numberRegex,
    method: HTTP_METHOD['PATCH'],
    name: 'cancel',
    scope: scopePrefix + 'booking.write',
    parent_id: 8,
  },
  {
    action_id: 12,
    path: booking + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get one',
    scope: scopePrefix + 'booking.read',
    parent_id: 8,
  },
  {
    action_id: 13,
    path: booking,
    method: HTTP_METHOD['GET'],
    name: 'get list',
    scope: scopePrefix + 'booking.read',
    parent_id: 8,
  },
  { action_id: 14, name: 'user', scope: scopePrefix + 'user.all' },
  {
    action_id: 15,
    path: user + '/me',
    method: HTTP_METHOD['GET'],
    name: 'get me',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 16,
    path: user + '/search',
    method: HTTP_METHOD['GET'],
    name: 'search',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 17,
    path: user + '/notification',
    method: HTTP_METHOD['GET'],
    name: 'get all notification',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 18,
    path: user + '/notification/status/bulk-read', // bad url  amirreza //fixed
    method: HTTP_METHOD['POST'],
    name: 'bulk set as read notification',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
  },
  {
    action_id: 19,
    path: user + '/notification/status' + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'update status',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
  },
  {
    action_id: 20,
    path: user + '/profile' + stringRegex,
    method: HTTP_METHOD['GET'],
    name: 'get profile',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 21,
    path: user + '/profile.me',
    method: HTTP_METHOD['GET'],
    name: 'get your profile',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 22,
    path: user + '/profile' + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'update your profile',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
  },
  {
    action_id: 23,
    path: user + '/settings/account',
    method: HTTP_METHOD['GET'],
    name: 'get account setting',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 24,
    path: user + '/settings/account',
    method: HTTP_METHOD['PUT'],
    name: 'edit account setting',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
  },
  {
    action_id: 25,
    path: user + '/settings/account/password',
    method: HTTP_METHOD['PUT'],
    name: 'change account password',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
    // dangerous: true,
  },
  {
    action_id: 26,
    path: user + '/settings/account/session' + stringRegex, // bad url amirreza // fixed
    method: HTTP_METHOD['DELETE'],
    name: 'delete account session',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
    // dangerous: true,
  },
  {
    action_id: 27,
    path: user + '/settings/account/emails',
    method: HTTP_METHOD['POST'],
    name: 'add email',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
    // dangerous: true,
  },
  {
    action_id: 28,
    path: user + '/settings/account/emails' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'remove email',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
    // dangerous: true,
  },
  {
    action_id: 29,
    path: user + '/settings/account',
    method: HTTP_METHOD['POST'], // bad url amirreza // reported to alireza for fixing this
    name: 'delete account',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
    // dangerous: true,
  },
  {
    action_id: 30,
    path: user + '/settings/notifications',
    method: HTTP_METHOD['GET'],
    name: 'get setting notifications',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 31,
    path: user + '/settings/notifications',
    method: HTTP_METHOD['PUT'],
    name: 'edit setting notifications',
    scope: scopePrefix + 'user.write',
    parent_id: 14,
  },
  {
    action_id: 32,
    path: user + '/settings/integrations',
    method: HTTP_METHOD['GET'],
    name: 'get all integrations',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 33,
    path: user + '/settings/integrations' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get one integration',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 34,
    path: user + '/settings/integrations' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get one integration',
    scope: scopePrefix + 'user.read',
    parent_id: 14,
  },
  {
    action_id: 35,
    name: 'workspace',
    scope: scopePrefix + 'workspace.all',
  },
  {
    action_id: 36,
    path: workspace,
    method: HTTP_METHOD['POST'],
    name: 'create',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 37,
    path: workspace,
    method: HTTP_METHOD['GET'],
    name: 'get all',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 38,
    path: workspace + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get one',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 39,
    path: workspace + '/invites',
    method: HTTP_METHOD['GET'],
    name: 'get invites',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 40,
    path: workspace + numberRegex + '/select',
    method: HTTP_METHOD['POST'],
    name: 'select',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 41,
    path: workspace + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 42,
    path: workspace + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'delete',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 43,
    path: workspace + numberRegex + '/logo',
    method: HTTP_METHOD['DELETE'],
    name: 'delete logo',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 44,
    path: workspace + numberRegex + '/logo',
    method: HTTP_METHOD['POST'],
    name: 'change logo',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 45,
    path: workspace + numberRegex + '/invite' + stringRegex,
    method: HTTP_METHOD['POST'],
    name: 'handle invites',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 46,
    path: workspace + numberRegex + '/manage.invite',
    method: HTTP_METHOD['POST'],
    name: 'manage invites',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 47,
    path: workspace + numberRegex + '/invite',
    method: HTTP_METHOD['POST'],
    name: 'invite users',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 48,
    path: workspace + numberRegex + '/search/user',
    method: HTTP_METHOD['GET'],
    name: 'search users',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 49,
    path: workspace + numberRegex + '/calendar',
    method: HTTP_METHOD['GET'],
    name: 'get calendar data',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 50,
    path: workspace + numberRegex + '/quick-access',
    method: HTTP_METHOD['GET'],
    name: 'get quick access',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 51,
    path: workspace + numberRegex + '/search/module',
    method: HTTP_METHOD['GET'],
    name: 'search in module',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 52,
    path: workspace + numberRegex + '/search/history',
    method: HTTP_METHOD['POST'],
    name: 'add to history',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 53,
    path: workspace + numberRegex + '/search/history' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'delete history',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 54,
    path: workspace + numberRegex + '/search/history',
    method: HTTP_METHOD['GET'],
    name: 'get histories',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 55,
    path: workspace + numberRegex + '/search/people',
    method: HTTP_METHOD['GET'],
    name: 'search in people',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 56,
    path: workspace + numberRegex + '/storage',
    method: HTTP_METHOD['GET'],
    name: 'get storage',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 57,
    path: workspace + numberRegex + '/set-block-event',
    method: HTTP_METHOD['POST'],
    name: 'set blocking event',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 58,
    path: workspace + '/profile' + stringRegex,
    method: HTTP_METHOD['GET'],
    name: 'get team profile',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 59,
    path: workspace + '/profile' + stringRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit team profile',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 60,
    name: 'meeting',
    scope: scopePrefix + 'meeting.all',
  },
  {
    action_id: 61,
    path: meeting + '/events' + stringRegex + '/start',
    method: HTTP_METHOD['POST'],
    name: 'start event',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 62,
    path: meeting + '/events' + stringRegex + '/end',
    method: HTTP_METHOD['POST'],
    name: 'end event',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 63,
    path: meeting,
    method: HTTP_METHOD['POST'],
    name: 'create',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 64,
    path: meeting + stringRegex + '/project',
    method: HTTP_METHOD['POST'],
    name: 'add to project',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 65,
    path: meeting + '/list',
    method: HTTP_METHOD['POST'], // bad method // not fixed
    name: 'list',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 66,
    path: meeting + '/search/all',
    method: HTTP_METHOD['POST'], // bad method // not fixed
    name: 'get all',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  // {
  //   action_id: 67,
  //   path: meeting + '/search/all',
  //   method: HTTP_METHOD['POST'], // bad method
  //   name: 'get all',
  //   scope: scopePrefix + 'meeting.read',
  //   parent_id: 60,
  // },
  {
    action_id: 68,
    path: meeting + stringRegex + '/req.permission',
    method: HTTP_METHOD['POST'],
    name: 'request for permission to access',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 69,
    path: meeting + stringRegex + '/attendee.requests',
    method: HTTP_METHOD['GET'],
    name: 'get attendee requests',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 70,
    path: meeting + '/event' + stringRegex + '/knock',
    method: HTTP_METHOD['POST'],
    name: 'knock',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 71,
    path: meeting + '/event' + stringRegex + '/join',
    method: HTTP_METHOD['POST'],
    name: 'join',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 72,
    path: meeting + stringRegex + '/decline',
    method: HTTP_METHOD['POST'],
    name: 'decline',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 73,
    path: meeting + stringRegex + '/reply.join.attendee.req',
    method: HTTP_METHOD['POST'],
    name: 'replay join attendee',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 74,
    path: meeting + stringRegex + '/agenda',
    method: HTTP_METHOD['GET'],
    name: 'get agendas',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 75,
    path: meeting + stringRegex + '/note',
    method: HTTP_METHOD['GET'],
    name: 'get notes',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 76,
    path: meeting + stringRegex + '/agenda/change.order',
    method: HTTP_METHOD['POST'],
    name: 'drag agenda',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 77,
    path: meeting + '/room' + stringRegex + '/init.mr',
    method: HTTP_METHOD['POST'],
    name: 'initiate room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 78,
    path: meeting + stringRegex + '/detail',
    method: HTTP_METHOD['GET'],
    name: 'get details',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 79,
    path: meeting + stringRegex + '/vote',
    method: HTTP_METHOD['POST'],
    name: 'vote',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 80,
    path: meeting + stringRegex + '/confirm',
    method: HTTP_METHOD['POST'],
    name: 'confirm',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 81,
    path: meeting + '/cancel',
    method: HTTP_METHOD['POST'],
    name: 'cancel',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 82,
    path: meeting + '/available-people',
    method: HTTP_METHOD['POST'],
    name: 'get available people',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 83,
    path: meeting + stringRegex + '/user.manage.invite',
    method: HTTP_METHOD['POST'],
    name: 'manage invites',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 84,
    path: meeting + stringRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 85,
    path: meeting + stringRegex + '/invite',
    method: HTTP_METHOD['GET'],
    name: 'handle invites',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 86,
    path: meeting + stringRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'delete',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 87,
    path: meeting + stringRegex + '/invite.user',
    method: HTTP_METHOD['POST'],
    name: 'invite user',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 88,
    path: meeting + stringRegex + '/attendee' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'delete attendee',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 89,
    path: meeting + stringRegex + '/share.permission',
    method: HTTP_METHOD['PUT'],
    name: 'share permission',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  // {
  //   action_id: 90,
  //   path: meeting + stringRegex + '/share.permission',
  //   method: HTTP_METHOD['GET'],
  //   name: 'get shared permissions',
  //   scope: scopePrefix + 'meeting.read',
  //   parent_id: 60,
  // },
  {
    action_id: 91,
    path: meeting + stringRegex + '/breakoutroom',
    method: HTTP_METHOD['POST'],
    name: 'create breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 92,
    path: meeting + stringRegex + '/breakoutroom/list',
    method: HTTP_METHOD['GET'],
    name: 'get breakout room list',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 93,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 94,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'delete breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 95,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex + '/mv.attendees.in',
    method: HTTP_METHOD['POST'],
    name: 'move attendees to breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 96,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex + '/mv.att.to.room',
    method: HTTP_METHOD['POST'],
    name: 'move attendees another breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 97,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex + '/open',
    method: HTTP_METHOD['POST'],
    name: 'open breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 98,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex + '/close',
    method: HTTP_METHOD['POST'],
    name: 'close breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 99,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex + '/join',
    method: HTTP_METHOD['POST'],
    name: 'join breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 100,
    path: meeting + stringRegex + '/breakoutroom' + stringRegex + '/leave',
    method: HTTP_METHOD['POST'],
    name: 'leave breakout room',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 101,
    path: meeting + '/template',
    method: HTTP_METHOD['POST'],
    name: 'create template',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 102,
    path: meeting + '/template',
    method: HTTP_METHOD['GET'],
    name: 'get all templates',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 103,
    path: meeting + '/template' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get a template',
    scope: scopePrefix + 'meeting.read',
    parent_id: 60,
  },
  {
    action_id: 104,
    path: meeting + '/template' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'remove template',
    scope: scopePrefix + 'meeting.write',
    parent_id: 60,
  },
  {
    action_id: 105,
    path: workspace + numberRegex + '/project',
    method: HTTP_METHOD['POST'],
    name: 'create project',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 106,
    path: workspace + numberRegex + '/project' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get project',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 107,
    path: workspace + numberRegex + '/project/get.all',
    method: HTTP_METHOD['GET'],
    name: 'get all projects',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 108,
    path: workspace + numberRegex + '/project' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'delete project',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 109,
    path: workspace + numberRegex + '/project' + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit project',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 110,
    path: workspace + numberRegex + '/project' + numberRegex + '/cover',
    method: HTTP_METHOD['POST'],
    name: 'upload project cover',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 111,
    path: workspace + numberRegex + '/project' + numberRegex + '/cover',
    method: HTTP_METHOD['DELETE'],
    name: 'delete project cover',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 112,
    path: workspace + numberRegex + '/project' + numberRegex + '/activity',
    method: HTTP_METHOD['GET'],
    name: 'get project activity',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  /*   {
    action_id: 113,
    path: workspace + numberRegex + '/project' + numberRegex + '/meetings',
    method: HTTP_METHOD['POST'], // bad method amirreza // route should be remove
    name: 'get project meetings',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  }, */
  {
    action_id: 114,
    path: workspace + numberRegex + '/project' + numberRegex + '/notes',
    method: HTTP_METHOD['GET'], // bad method amirreza //fixed
    name: 'get project notes',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 115,
    path: workspace + numberRegex + '/project' + numberRegex + '/chats',
    method: HTTP_METHOD['GET'],
    name: 'get project chats',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 116,
    path: workspace + numberRegex + '/project/recent',
    method: HTTP_METHOD['GET'],
    name: 'get recent projects',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 117,
    path: workspace + numberRegex + '/project' + numberRegex + '/handle.invite',
    method: HTTP_METHOD['GET'],
    name: 'handle project invites',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 118,
    path: workspace + numberRegex + '/document/upsert.block',
    method: HTTP_METHOD['POST'],
    name: 'upsert document',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 119,
    path: workspace + numberRegex + '/document' + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'update document note',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 120,
    path: workspace + numberRegex + '/document' + numberRegex,
    method: HTTP_METHOD['DELETE'], // bad method and url alireza //fixed
    name: 'remove document',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 121,
    path: workspace + numberRegex + '/document' + numberRegex + '/remove',
    method: HTTP_METHOD['POST'],
    name: 'remove document',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 122,
    path: workspace + numberRegex + '/document/upload',
    method: HTTP_METHOD['POST'],
    name: 'upload document',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 123,
    path: workspace + numberRegex + '/document/notes',
    method: HTTP_METHOD['GET'], // bad method alireza // fixed
    name: 'get all document notes',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 124,
    path: workspace + numberRegex + '/document' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get document',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 125,
    path: workspace + numberRegex + '/document' + numberRegex + '/duplicate',
    method: HTTP_METHOD['POST'],
    name: 'duplicate document',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 126,
    path: workspace + numberRegex + '/document' + numberRegex + '/handle.invite',
    method: HTTP_METHOD['POST'],
    name: 'handle document invites',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 127,
    path: workspace + numberRegex + '/settings/profile',
    method: HTTP_METHOD['GET'], // bad url alireza // fixed
    name: 'get workspace setting',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 128,
    path: workspace + numberRegex + '/settings/appearance',
    method: HTTP_METHOD['GET'],
    name: 'get appearance setting',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 129,
    path: workspace + numberRegex + '/settings/appearance',
    method: HTTP_METHOD['PUT'],
    name: 'update appearance setting',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 130,
    path: workspace + numberRegex + '/settings/roles',
    method: HTTP_METHOD['POST'],
    name: 'create workspace roles',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 131,
    path: workspace + numberRegex + '/settings/roles',
    method: HTTP_METHOD['GET'],
    name: 'get workspace roles',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 132,
    path: workspace + numberRegex + '/settings/roles' + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit workspace roles',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 133,
    path: workspace + numberRegex + '/settings/roles' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'remove workspace roles',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 134,
    path: workspace + numberRegex + 'settings/members',
    method: HTTP_METHOD['GET'], // bad url alireza // fixed
    name: 'get all workspace members',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 135,
    path: workspace + numberRegex + '/settings/members/change-role' + numberRegex + numberRegex,
    method: HTTP_METHOD['PUT'], // bad url alireza // fixed
    name: 'change member role',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 136,
    path: workspace + numberRegex + '/settings/members' + numberRegex,
    method: HTTP_METHOD['DELETE'], // bad url alireza // fixed
    name: 'remove member',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 137,
    path: workspace + numberRegex + '/contact',
    method: HTTP_METHOD['POST'],
    name: 'add contact',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 138,
    path: workspace + numberRegex + '/contact/username',
    method: HTTP_METHOD['POST'], // bad url amirreza // fixed
    name: 'add contact by username',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 139,
    path: workspace + numberRegex + '/contact' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get contact',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 140,
    path: workspace + numberRegex + '/contact',
    method: HTTP_METHOD['GET'],
    name: 'get all contacts',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 141,
    path: workspace + numberRegex + '/contact' + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit contact',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 142,
    path: workspace + numberRegex + '/contact' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'remove contact',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 143,
    path: workspace + numberRegex + '/contact/search',
    method: HTTP_METHOD['GET'], // bad method amirreza //fixed
    name: 'search contacts',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 144,
    path: workspace + numberRegex + '/contact' + numberRegex + '/activity',
    method: HTTP_METHOD['GET'], // wrong spell by amirreza // fixed by alamian
    name: 'get contact activity',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 145,
    path: workspace + numberRegex + '/contact' + numberRegex + '/chats',
    method: HTTP_METHOD['GET'],
    name: 'get contact chats',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 146,
    path: workspace + numberRegex + '/contact/group',
    method: HTTP_METHOD['POST'],
    name: 'create contact group',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 147,
    path: workspace + numberRegex + '/contact/group' + numberRegex,
    method: HTTP_METHOD['PUT'],
    name: 'edit contact group',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 148,
    path: workspace + numberRegex + '/contact/group',
    method: HTTP_METHOD['GET'],
    name: 'get all contact group',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 149,
    path: workspace + numberRegex + '/contact/group' + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get contact group',
    scope: scopePrefix + 'workspace.read',
    parent_id: 35,
  },
  {
    action_id: 150,
    path: workspace + numberRegex + '/contact/group' + numberRegex + '/user',
    method: HTTP_METHOD['POST'],
    name: 'add user to contact group',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 151,
    path: workspace + numberRegex + '/contact/group' + numberRegex + '/user' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'remove user from contact group',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 152,
    path: workspace + numberRegex + '/contact/group' + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'remove contact group',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 153,
    path: workspace + numberRegex + '/contact/group' + numberRegex + '/avatar',
    method: HTTP_METHOD['DELETE'],
    name: 'remove contact group avatar',
    scope: scopePrefix + 'workspace.write',
    parent_id: 35,
  },
  {
    action_id: 154,
    name: 'template availability',
    scope: scopePrefix + 'templateAvailability.all',
  },
  {
    action_id: 155,
    path: templateAvailability,
    method: HTTP_METHOD['POST'],
    name: 'create template',
    scope: scopePrefix + 'templateAvailability.write',
    parent_id: 154,
  },
  {
    action_id: 156,
    path: templateAvailability + numberRegex,
    method: HTTP_METHOD['PATCH'],
    name: 'edit template',
    scope: scopePrefix + 'templateAvailability.write',
    parent_id: 154,
  },
  {
    action_id: 157,
    path: templateAvailability + numberRegex,
    method: HTTP_METHOD['DELETE'],
    name: 'remove template',
    scope: scopePrefix + 'templateAvailability.write',
    parent_id: 154,
  },
  {
    action_id: 158,
    path: templateAvailability + numberRegex,
    method: HTTP_METHOD['GET'],
    name: 'get template',
    scope: scopePrefix + 'templateAvailability.read',
    parent_id: 154,
  },
  {
    action_id: 159,
    path: templateAvailability,
    method: HTTP_METHOD['GET'],
    name: 'search template',
    scope: scopePrefix + 'templateAvailability.read',
    parent_id: 154,
  },
  {
    action_id: 160,
    name: 'room',
    scope: scopePrefix + 'room.all',
  },
  {
    action_id: 161,
    path: room,
    method: HTTP_METHOD['POST'],
    name: 'create room',
    scope: scopePrefix + 'room.write',
    parent_id: 160,
  },
  {
    action_id: 162,
    path: room + stringRegex,
    method: HTTP_METHOD['PATCH'],
    name: 'edit room',
    scope: scopePrefix + 'room.write',
    parent_id: 160,
  },
  {
    action_id: 163,
    path: room + stringRegex + '/detail',
    method: HTTP_METHOD['GET'],
    name: 'get room details',
    scope: scopePrefix + 'room.read',
    parent_id: 160,
  },
  {
    action_id: 164,
    path: room + '/user/my',
    method: HTTP_METHOD['GET'], // bad url alireza
    name: 'get user rooms',
    scope: scopePrefix + 'room.read',
    parent_id: 160,
  },
  {
    action_id: 165,
    path: room,
    method: HTTP_METHOD['GET'],
    name: 'get all rooms',
    scope: scopePrefix + 'room.read',
    parent_id: 160,
  },
  {
    action_id: 166,
    name: 'sharing',
    scope: scopePrefix + 'sharing.all',
  },
  {
    action_id: 167,
    path: sharing,
    method: HTTP_METHOD['POST'],
    name: 'create',
    scope: scopePrefix + 'room.write',
    parent_id: 166,
  },
  {
    action_id: 168,
    path: sharing,
    method: HTTP_METHOD['DELETE'],
    name: 'delete',
    scope: scopePrefix + 'room.write',
    parent_id: 166,
  },
  {
    action_id: 169,
    path: sharing,
    method: HTTP_METHOD['PATCH'],
    name: 'edit',
    scope: scopePrefix + 'room.write',
    parent_id: 166,
  },
  {
    action_id: 170,
    path: sharing + '/setting',
    method: HTTP_METHOD['PATCH'], // bad url alireza // fixed
    name: 'update url',
    scope: scopePrefix + 'room.write',
    parent_id: 166,
  },
  {
    action_id: 171,
    path: sharing,
    method: HTTP_METHOD['GET'],
    name: 'get all',
    scope: scopePrefix + 'room.read',
    parent_id: 166,
  },
]
