import { Prisma } from '@prisma/client'
import { MODULE_KEY } from '../../../../shared-models/index.js'

export function enumToArray<U extends string, T extends { [K in keyof T]: U }>(
  _enumType: T,
  values: [...(Prisma.moduleCreateArgs['data'] & { key: U })[]],
): (Prisma.moduleCreateArgs['data'] & { key: U })[] {
  return values
}

export const modules = [
  {
    name: 'System',
    key: MODULE_KEY.system,
    description: 'See your schedule, Responds and etc.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    key: MODULE_KEY.meeting,
    name: 'Schedule Meeting',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    version: '1',
  },
  {
    key: MODULE_KEY.chat,
    name: 'Messages ',
    description: `Supplemental actions within the card are explicitly called chat out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    key: MODULE_KEY.meeting_room,
    name: 'Meeting Room',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    key: MODULE_KEY.contact,
    name: 'Contacts',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    key: MODULE_KEY.file,
    name: 'Files',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    key: MODULE_KEY.document,
    name: 'Document',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    key: MODULE_KEY.note,
    name: 'Notes',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    parent: { connect: { key: MODULE_KEY.document } },
    version: '1',
  },
  {
    key: MODULE_KEY.agenda,
    name: 'Agenda',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: false,
    parent: { connect: { key: MODULE_KEY.meeting } },
    version: '1',
  },
  {
    key: MODULE_KEY.form,
    name: 'Form',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: false,
    parent: { connect: { key: MODULE_KEY.meeting } },
    version: '1',
  },
  {
    key: MODULE_KEY.document_template,
    name: 'Document Template',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: false,
    parent: { connect: { key: MODULE_KEY.document } },
    version: '1',
  },
  {
    key: MODULE_KEY.project,
    name: 'Projects',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    key: MODULE_KEY.opportunity,
    name: 'Opportunities',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    key: MODULE_KEY.service,
    name: 'Services',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    key: MODULE_KEY.polls,
    name: 'Polls',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    version: '1',
  },
  {
    key: MODULE_KEY.instant_call,
    name: 'Meet Now',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    version: '1',
  },

  {
    key: MODULE_KEY.room,
    name: 'Rooms',
    description: 'Members with this access will be see Online Users',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    key: MODULE_KEY.user_profile,
    name: 'User Profile',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    version: '1',
  },
  {
    name: 'Workspace',
    key: MODULE_KEY.workspace,
    description: 'See your schedule, Responds and etc.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    key: MODULE_KEY.workspace_profile,
    name: 'Team Profile',
    description: `Supplemental actions within the card are explicitly called out using icons,
       text, and UI controls, typically placed at the bottom of the card.`,
    status: 1,
    is_sys: true,
    // parent: { connect: { key: MODULE_KEY.workspace } },
    version: '1',
  },
  {
    key: MODULE_KEY.breakout_room,
    name: 'Breakout Rooms',
    description: 'Breakout rooms going to be available in the meeting room and schedule meeting',
    status: 1,
    parent: { connect: { key: MODULE_KEY.meeting } },
    is_sys: true,
    version: '1',
  },
  {
    key: MODULE_KEY.share_screen,
    name: 'Presents',
    description: 'You can Share the Screen during the meeting',
    status: 1,
    parent: { connect: { key: MODULE_KEY.meeting } },
    is_sys: true,
    version: '1',
  },
  {
    key: MODULE_KEY.meeting_recording,
    name: 'Recording',
    description: `Recordings are Available on Meeting Detail Page after the meeting ends,
       Only the organizer can record the meeting`,
    status: 1,
    parent: { connect: { key: MODULE_KEY.meeting } },
    is_sys: true,
    version: '1',
  },
  {
    key: MODULE_KEY.raise_hand,
    name: 'Raise Hand',
    description: 'Raise hand will be available Under the meeting tools',
    status: 1,
    parent: { connect: { key: MODULE_KEY.meeting } },
    is_sys: true,
    version: '1',
  },

  {
    key: MODULE_KEY.virtual_background,
    name: 'Virtual Background',
    description: 'Attendees Background will be Blurred',
    status: 1,
    parent: { connect: { key: MODULE_KEY.meeting } },
    is_sys: true,
    version: '1',
  },
  {
    key: MODULE_KEY.stripe,
    name: 'Stripe',
    subtitle:
      'Connect with Stripe to manage your transactions, facilitate secure payments, and enhance your billing procedures directly within Coffee.',
    description:
      'Connect with Stripe to manage your transactions, facilitate secure payments, and enhance your billing procedures directly within Coffee.',
    status: 1,
    version: '1',
  },
  {
    name: 'Google Calendar',
    subtitle: 'Sync your schedules and events, streamline your meetings and manage your availability in Coffee.',
    key: MODULE_KEY.google_calendar,
    description: 'Sync your schedules and events, streamline your meetings and manage your availability in Coffee.',
    status: 1,
    module_category: {
      connectOrCreate: {
        where: { key: 'Calendar' },
        create: { name: 'Calendar', key: 'Calendar' },
      },
    },
    version: '1',
  },
  {
    name: 'Google Contacts',
    subtitle: 'Import contacts from Google Contacts into Coffee.',
    key: MODULE_KEY.google_contacts,
    description: 'Import contacts from Google Contacts into Coffee.',
    status: 1,
    module_category: {
      connectOrCreate: {
        where: { key: 'Contacts' },
        create: { name: 'Contacts', key: 'Contacts' },
      },
    },
    version: '1',
  },
  {
    name: 'Slack',
    subtitle: 'Use Slack to start and join Coffee sessions and get Coffee notifications.',
    key: MODULE_KEY.slack,
    description: 'Use Slack to start and join Coffee sessions and get Coffee notifications.',
    status: 1,
    module_category: {
      connectOrCreate: {
        where: { key: 'Slack' },
        create: { name: 'Slack', key: 'Slack' },
      },
    },
    version: '1',
  },
  {
    name: 'Zapier',
    subtitle: 'Automate work with connecting Coffee with thousands of the most popular apps.',
    key: MODULE_KEY.zapier,
    description: 'Automate work with connecting Coffee with thousands of the most popular apps.',
    status: 1,
    module_category: {
      connectOrCreate: {
        where: { key: 'Zapier' },
        create: { name: 'Zapier', key: 'Zapier' },
      },
    },
    version: '1',
  },
  {
    name: 'Clio',
    subtitle: 'Connect from anywhere and eliminate administrative work in legal practice.',
    key: MODULE_KEY.clio,
    description: 'Connect from anywhere and eliminate administrative work in legal practice.',
    status: 1,
    version: '1',
  },
  {
    name: 'Outlook Calendar',
    subtitle: 'Sync your schedules and events, streamline your meetings and manage your availability in Coffee.',
    // eslint-disable-next-line quotes
    description: 'Sync your schedules and events, streamline your meetings and manage your availability in Coffee.',
    key: MODULE_KEY.outlook_calendar,
    is_on_marketplace: true,
    module_category: {
      connectOrCreate: {
        where: { key: 'Calendar' },
        create: { name: 'Calendar', key: 'Calendar' },
      },
    },
    status: 1,
    version: '1',
  },
  {
    name: 'Calendar',
    key: MODULE_KEY.calendar,
    description: 'See your schedule, Responds and etc.',
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    name: 'Embed',
    key: MODULE_KEY.embed,
    description: 'See your schedule, Responds and etc.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    name: 'Notification Preference',
    key: MODULE_KEY.notification_pref,
    description: 'See your schedule, Responds and etc.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    name: 'Marketplace',
    key: MODULE_KEY.marketplace,
    description: 'See your schedule, Responds and etc.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    name: 'Booking',
    key: MODULE_KEY.booking,
    description: 'Booking module.',
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    name: 'Private File',
    key: MODULE_KEY.private_file,
    description: 'Private File module.',
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    name: 'Folder',
    key: MODULE_KEY.folder,
    description: 'Folder File module.',
    status: 1,
    is_sys: true,
    is_visible: true,
    version: '1',
  },
  {
    name: 'Usergroup',
    key: MODULE_KEY.usergroup,
    description: 'Usergroup module.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    name: 'Task',
    key: MODULE_KEY.task,
    description: 'Task module.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    name: 'Click up',
    key: MODULE_KEY.clickup,
    description: 'Click up module.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
  {
    name: 'Magic Link',
    key: MODULE_KEY.magicLink,
    description: 'Magic Link module.',
    status: 1,
    is_sys: true,
    is_visible: false,
    version: '1',
  },
] satisfies (Prisma.moduleCreateArgs['data'] & { key: MODULE_KEY })[]

enumToArray(MODULE_KEY, modules)
