export enum EMimeDB {
  image = 'image',
  video = 'video',
  audio = 'audio',
  font = 'font',
  common = 'common',
  text = 'text',
}
export type TMimeDB = keyof typeof EMimeDB
export const mimeDB = {
  text: [
    {
      mime: 'text/vnd.trolltech.linguist',
      exts: ['ts'],
    },
  ],
  image: [
    { abbreviation: 'APNG', mime: 'image/apng', exts: ['apng'] },
    { abbreviation: 'AVIF', mime: 'image/avif', exts: ['avif'] },
    { abbreviation: 'GIF', mime: 'image/gif', exts: ['gif'] },
    { abbreviation: 'JPEG', mime: 'image/jpeg', exts: ['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp'] },
    { abbreviation: 'PNG', mime: 'image/png', exts: ['png'] },
    { abbreviation: 'SVG', mime: 'image/svg+xml', exts: ['svg'] },
    { abbreviation: 'BMP', mime: 'image/bmp', exts: ['bmp'] },
    { abbreviation: 'ICO', mime: 'image/x-icon', exts: ['ico', 'cur'] },
    { abbreviation: 'TIFF', mime: 'image/tiff', exts: ['tif', 'tiff'] },
  ],
  video: [
    { abbreviation: 'Apple Mpeg URL', mime: 'application/vnd.apple.mpegurl', exts: ['m3u', 'm3u8'] },
    { abbreviation: 'Mpeg URL', mime: 'application/x-mpegurl', exts: ['m3u', 'm3u8'] },
    { abbreviation: '3gp', mime: 'video/3gpp', exts: ['3gp'] },
    { abbreviation: 'MP4', mime: 'video/mp4', exts: ['mp4', 'm4a', 'm4p', 'm4b', 'm4r', 'm4v'] },
    { abbreviation: 'MPEG', mime: 'video/mpeg', exts: ['m1v'] },
    { abbreviation: 'OGG', mime: 'video/ogg', exts: ['ogg'] },
    { abbreviation: 'MOV', mime: 'video/quicktime', exts: ['mov', 'qt'] },
    { abbreviation: 'WEBM', mime: 'video/webm', exts: ['webm'] },
    { abbreviation: 'M4V', mime: 'video/x-m4v', exts: ['m4v'] },
    { abbreviation: 'ASF', mime: 'video/ms-asf', exts: ['asf', 'wma', 'wmv'] },
    { abbreviation: 'WMV', mime: 'video/x-ms-wmv', exts: ['wmv'] },
    { abbreviation: 'AVI', mime: 'video/x-msvideo', exts: ['avi'] },
    { abbreviation: 'MKV', mime: 'video/mkv', exts: ['mkv'] },
  ],
  audio: [
    { abbreviation: 'AU', mime: 'audio/basic', exts: ['au', 'snd'] },
    { abbreviation: 'Linear PCM', mime: 'auido/L24', exts: ['pcm'] },
    { abbreviation: 'MID', mime: 'audio/mid', exts: ['mid', 'rmi'] },
    { abbreviation: 'MP3', mime: 'audio/mpeg', exts: ['mp3'] },
    { abbreviation: 'MP3', mime: 'audio/mp3', exts: ['mp3'] },
    { abbreviation: 'MP4', mime: 'audio/mp4', exts: ['mp4'] },
    { abbreviation: 'AIF', mime: 'audio/x-aiff', exts: ['aif', 'aifc', 'aiff'] },
    { abbreviation: 'aiff', mime: 'audio/x-mpegurl', exts: ['m3u'] },
    { abbreviation: 'RA', mime: 'audio/vnd.rn-realaudio', exts: ['ra', 'ram'] },
    { abbreviation: 'Ogg Vorbis', mime: 'audio/ogg', exts: ['ogg', 'oga'] },
    { abbreviation: 'Vorbis', mime: 'audio/vorbis', exts: ['ogg'] },
    { abbreviation: 'Waveform', mime: 'audio/vnd.wav', exts: ['wav'] },
    { abbreviation: 'AAC', mime: 'audio/aac', exts: ['aac'] },
    { abbreviation: 'Opus', mime: 'audio/opus', exts: ['opus'] },
    { abbreviation: 'WEBM', mime: 'audio/webm', exts: ['weba'] },
    { abbreviation: '3GP', mime: 'audio/3gpp', exts: ['3gp'] },
    { abbreviation: 'MIDI', mime: 'audio/midi audio/x-midi', exts: ['mid', 'midi'] },
  ],
  font: [
    { abbreviation: 'EOT', mime: 'application/vnd.ms-fontobject', exts: ['eot'] },
    { abbreviation: 'WOFF', mime: 'application/font-woff', exts: ['woff'] },
    { abbreviation: 'WOFF2', mime: 'application/font-woff2', exts: ['woff2'] },
    { abbreviation: 'OTF', mime: 'application/x-font-otf', exts: ['otf'] },
    { abbreviation: 'TTF', mime: 'application/x-font-ttf', exts: ['ttf'] },
  ],
  common: [
    { abbreviation: 'ABW', mime: 'application/x-abiword', exts: ['abw'] },
    { abbreviation: 'ARC', mime: 'application/x-freearc', exts: ['arc'] },
    { abbreviation: 'AZW', mime: 'application/vnd.amazon.ebook', exts: ['azw'] },
    { abbreviation: 'BIN', mime: 'application/octet-stream', exts: ['bin'] },
    { abbreviation: 'BZ', mime: 'application/x-bzip', exts: ['bz'] },
    { abbreviation: 'BZ2', mime: 'application/x-bzip2', exts: ['bz2'] },
    { abbreviation: 'CDA', mime: 'application/x-cdf', exts: ['cda'] },
    { abbreviation: 'CSH', mime: 'application/x-csh', exts: ['csh'] },
    { abbreviation: 'CSS', mime: 'text/css', exts: ['css'] },
    { abbreviation: 'CSV', mime: 'text/csv', exts: ['csv'] },
    { abbreviation: 'DOC', mime: 'application/msword', exts: ['doc'] },
    {
      abbreviation: 'DOCX',
      mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      exts: ['docx'],
    },
    { abbreviation: 'EOT', mime: 'application/vnd.ms-fontobject', exts: ['eot'] },
    { abbreviation: 'EPUB', mime: 'application/epub+zip', exts: ['epub'] },
    { abbreviation: 'GZ', mime: 'application/gzip', exts: ['gz'] },
    { abbreviation: 'HTML', mime: 'text/html', exts: ['htm', 'html'] },
    { abbreviation: 'ICS', mime: 'text/calendar', exts: ['ics'] },
    { abbreviation: 'JAR', mime: 'application/java-archive', exts: ['jar'] },
    { abbreviation: 'JAVASCRIPT', mime: 'text/javascript', exts: ['js', 'mjs'] },
    { abbreviation: 'JSON', mime: 'application/json', exts: ['json'] },
    { abbreviation: 'JSONOLD', mime: 'application/ld+json', exts: ['jsonld'] },
    { abbreviation: 'MPKG', mime: 'application/vnd.apple.installer+xml', exts: ['mpkg'] },
    { abbreviation: 'ODP', mime: 'application/vnd.oasis.opendocument.presentation', exts: ['odp'] },
    { abbreviation: 'ODS', mime: 'application/vnd.oasis.opendocument.spreadsheet', exts: ['ods'] },
    { abbreviation: 'ODT', mime: 'application/vnd.oasis.opendocument.text', exts: ['odt'] },
    { abbreviation: 'OGG', mime: 'application/ogg', exts: ['ogx'] },
    { abbreviation: 'PDF', mime: 'application/pdf', exts: ['pdf'] },
    { abbreviation: 'PHP', mime: 'application/x-httpd-php', exts: ['php'] },
    {
      abbreviation: 'PPT',
      mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      exts: ['pptx'],
    },
    { abbreviation: 'RAR', mime: 'application/vnd.rar', exts: ['rar'] },
    { abbreviation: 'RTF', mime: 'application/rtf', exts: ['rtf'] },
    { abbreviation: 'SH', mime: 'application/x-sh', exts: ['sh'] },
    { abbreviation: 'SVG', mime: 'image/svg+xml', exts: ['svg'] },
    { abbreviation: 'SWF', mime: 'application/x-shockwave-flash', exts: ['swf'] },
    { abbreviation: 'TAR', mime: 'application/x-tar', exts: ['tar'] },
    { abbreviation: 'TXT', mime: 'text/plain', exts: ['txt'] },
    { abbreviation: 'VSD', mime: 'application/vnd.visio', exts: ['vsd'] },
    { abbreviation: 'XHTML', mime: 'application/xhtml+xml', exts: ['xhtml'] },
    { abbreviation: 'XLS', mime: 'application/vnd.ms-excel', exts: ['xls'] },
    {
      abbreviation: 'XLSX',
      mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      exts: ['xlsx'],
    },
    { abbreviation: 'XLM', mime: 'application/xml', exts: ['xml'] },
    { abbreviation: 'XLM', mime: 'text/xml', exts: ['xml'] },
    { abbreviation: 'XUL', mime: 'application/vnd.mozilla.xul+xml', exts: ['xul'] },
    { abbreviation: 'zip', mime: 'application/zip', exts: ['zip'] },
    { abbreviation: '7ZIP', mime: 'application/x-7z-compressed', exts: ['7z'] },
    { abbreviation: 'DTD', mime: 'application/xml-dtd', exts: ['dtd'] },
    { abbreviation: 'EXE', mime: 'application/octet-stream', exts: ['exe'] },
    { abbreviation: 'Hqx', mime: 'application/mac-binhex40', exts: ['hqx'] },
    { abbreviation: 'PL', mime: 'application/x-perl', exts: ['pl'] },
    { abbreviation: 'PS', mime: 'application/postscript', exts: ['ps'] },
    { abbreviation: 'RTF', mime: 'application/rtf', exts: ['rtf'] },
    { abbreviation: 'RDF', mime: 'application/rdf', exts: ['rdf'] },
    { abbreviation: 'RDF', mime: 'application/rdf+xml', exts: ['rdf'] },
    { abbreviation: 'SGML', mime: 'text/sgml', exts: ['sgml'] },
    { abbreviation: 'SIT', mime: 'application/x-stuffit', exts: ['sit'] },
    { abbreviation: 'TAR', mime: 'application/x-tar', exts: ['tar', 'gz', 'tgz'] },
    { abbreviation: 'TSV', mime: 'text/tab-separated-values', exts: ['tsv'] },
  ],
}
