export const regexPatterns: { [key: string]: RegExp } = {
  meetingSubject: /^[0-9a-zA-Z-_.\s]+$/g,
  workspaceSubdomain: /^[a-z][0-9a-z]{2,}$/,
  usernameFormat: /^[0-9a-zA-Z]{2,}$/g,
  colorHex: /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
  removeHttp: /(^\w+:|^)\/\//,
  emailFormat: /^[a-zA-Z0-9._+-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]{2,6}$/g,
  serviceUrlFormat: /^\w(\w| \d|[-_.]){3,62}$/g,
  usernameReplaceFormat: /[^A-Za-z0-9]/g,
  rocketChatLanguage: /^[a-z]{2}-[A-Z]{2}$/g,
  domainFormat: /^[a-zA-Z0-9._-]+\.[a-zA-Z]{2,6}$/g,
  download_file_special_character_replace: /[\\:/?*"|\s]/g, // share to front if you want to change it
  file_and_folder_special_characters: /[^a-zA-Z0-9_.\s]+/g,
  password: /^(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*$/,
  duplicateModuleRecordName: /\s\((\d+)\)/g,
  bucketInvalidCharacters: /[-!@#$%^&*()_+=~`/\\,|]/g,
  addDashToHash: /.{3}(?!$)/g,
  customDomainPattern: /^\w[\w\-.]+\.\w+$/g,
  google_meet: /(https:\/\/|http:\/\/)?meet\.google\.com\/.*/g,
  zoom_meet: /(https:\/\/|http:\/\/)?.+zoom.us\/.*/g,
  webex_meet: /(https:\/\/|http:\/\/)?.*\.webex\.com\/.*/g,
  skype_meet: /(https:\/\/|http:\/\/)?.*\.skype\.com\/.*/g,
  google_meeting_id: /[wxyz-]/g,
  calendar_tag: /^(LIVE:\s|ENDED:\s|CANCELED:\s|MISSED:\s)/g,
  youtube_id: /(vi\/|v=|\/v\/|youtu\.be\/|\/embed\/)/,
  divideByColonAndDot: /[:.]/,
  isoStringDateTime: /(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)/,
}
