export type ISearchableModule =
  | 'meeting_upcoming'
  | 'meeting_past'
  | 'meeting_poll'
  | 'service'
  | 'room'
  | 'note'
  | 'project'
  | 'opportunity'
  | 'contact'
  | 'usergroup'
  | 'private_file'
  | 'folder'
